### PR TITLE
Closes #15 - Prevent NPM warning over peerDependency for React 16

### LINKED ISSUE #15: Support React 16
```
npm WARN shiitake@2.1.1 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
```

### PR DESCRIPTION
**Pull request by lostthetrail**
@bsidelinger912 mind taking a look?
Closes #15

### CODE REVIEW

**Comment by bsidelinger912** [comment]
this looks great, I'll test ASAP, then merge and publish.  Thanks!

**Comment by lostthetrail** [comment]
@bsidelinger912 Thanks!

**Comment by bsidelinger912** [comment]
@lostthetrail I just grabbed the react dependency as while it's unlikely, Shiitake can be used without react DOM.  I just published v2.2.1 and tested using yarn with React 16 (and 15), and it looks good to me.  Please let me know when you have a chance to try it.

**Comment by lostthetrail** [comment]
Looks to be working with your 2.2.1 changes. Cheers!

**Pull request closed without merging**
